services:
  app:
    build: .
    volumes:
      - ./:/root/take_home_project
    command: python3 app.py
    ports:
      - "8888:8888"
    env_file:
      - ./local.env
  postgres:
    image: postgres:15.2
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./local.env
  web:
    build: ./my-app 
    ports: 
      - "3000:3000"
    volumes: 
      - ./my-app:/user/src/app
    depends_on: 
      - app
